name: Node

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm ci
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          check-version: true
          token: ${{ secrets.NPM_TOKEN }}
